# Don't edit the `bin` list manually! It is updated by `cargo run -- dev update`. This comment line will be stripped in `rustlings init`.
bin = [
  { name = "intro1", path = "../exercises/intro/intro1.rs" },
  { name = "intro1_sol", path = "../solutions/intro/intro1.rs" },
  { name = "01_basic_modulo", path = "../exercises/math/01_basic_modulo.md" },
  { name = "01_basic_modulo_sol", path = "../solutions/math/01_basic_modulo.md" },
  { name = "02_negative_modulo", path = "../exercises/math/02_negative_modulo.md" },
  { name = "02_negative_modulo_sol", path = "../solutions/math/02_negative_modulo.md" },
  { name = "01_simple_addition", path = "../exercises/circom/01_simple_addition.circom" },
  { name = "01_simple_addition_sol", path = "../solutions/circom/01_simple_addition.circom" },
]

[package]
name = "exercises"
edition = "2021"
# Don't publish the exercises on crates.io!
publish = false
